torchbox/verdant-rca

django-verdant/requirements.txt, vagrant/provision.sh
Changes to make the project buildable on vagrant for new developers. Deals with repercussions from changes to Vagrantfile, and gradual maintenance.
=> Settings changes

django-verdant/rca/models.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/791
=> [791] Append year to image caption

django-verdant/rca/models.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/791
=> [791] tuning boost scores for search so relevant pages are relevant

django-verdant/rca_ee/templates/rca_ee/form_page.html, django-verdant/rca_ee/wtforms.py, django-verdant/rcasite/settings/base.py, django-verdant/requirements.txt
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/795
=> [795] adding recaptcha to all of our form pages

django-verdant/rcasite/settings/base.py, django-verdant/taxonomy/migrations/0001_initial.py, django-verdant/taxonomy/migrations/0002_initial_data.py, django-verdant/taxonomy/migrations/0003_auto_20160615_1451.py, django-verdant/taxonomy/migrations/0004_auto_20160615_1455.py, django-verdant/taxonomy/migrations/0005_populate_programme_graduation_year.py, django-verdant/taxonomy/migrations/0006_auto_20160615_1502.py, django-verdant/taxonomy/migrations/0007_deduplicate_schools.py, django-verdant/taxonomy/migrations/0008_auto_20160615_1506.py, django-verdant/taxonomy/migrations/0009_auto_20160621_1357.py, django-verdant/taxonomy/migrations/0010_schoolhistoricaldisplayname.py, django-verdant/taxonomy/migrations/0011_auto_20160621_1448.py, django-verdant/taxonomy/migrations/0012_deduplicate_programmes.py, django-verdant/taxonomy/migrations/0013_programme_disabled.py, django-verdant/taxonomy/migrations/0014_populate_programme_disabled.py, django-verdant/taxonomy/migrations/0015_auto_20160630_1055.py, django-verdant/taxonomy/migrations/0016_programmehistoricaldisplayname.py, django-verdant/taxonomy/migrations/0017_auto_20160630_1103.py, django-verdant/taxonomy/models.py
Moving schools, programmes and areas into snippets
=> Taxonomy models

django-verdant/rca/migrations/0025_auto_20160701_1415.py, django-verdant/rca/migrations/0026_auto_20160701_1417.py, django-verdant/rca/migrations/0027_auto_20160701_1513.py, django-verdant/rca/migrations/0028_auto_20160701_1714.py, django-verdant/rca/migrations/0029_auto_20160705_1240.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/staff_page.html, django-verdant/rca/templatetags/rca_tags.py
=> Convert staff profiles to use new taxonomy

django-verdant/rca/migrations/0025_taxonomy_school_page_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_school_page_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_school_page_remove_old_fields.py, django-verdant/rca/migrations/0028_taxonomy_programme_page_add_new_fields.py, django-verdant/rca/migrations/0029_taxonomy_programme_page_migrate_data.py, django-verdant/rca/migrations/0030_taxonomy_programme_page_remove_old_fields.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/school_page.html
=> Update School/Progamme pages for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_news_item_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_news_item_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_news_item_remove_old_fields.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/includes/modules/news-meta-data.html
=> Update news pages for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_press_release_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_press_release_migrate_data.py, django-verdant/rca/migrations/0027_toxonomy_press_release_remove_old_fields.py, django-verdant/rca/models.py
=> Convert press releases to use new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_research_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_research_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_research_remove_old_fields.py, django-verdant/rca/models.py
Must be deployed with ProgrammePage/NewsItem taxonomy updates: #39 #41 
TODO:
=> Update ResearchItem for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_event_item_add_new_fields.py, django-verdant/rca/migrations/0025_taxonomy_standard_page_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_event_item_migrate_data.py, django-verdant/rca/migrations/0026_taxonomy_standard_page_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_event_item_remove_old_fields.py, django-verdant/rca/migrations/0027_taxonomy_standard_page_remove_old_fields.py, django-verdant/rca/migrations/0032_merge.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/standard_index.html, django-verdant/rca/templatetags/rca_tags.py
This is a rollup of #43 and #44. Deploying on monday
=> Taxonomy rollup for monday

django-verdant/rca/migrations/0025_taxonomy_event_item_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_event_item_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_event_item_remove_old_fields.py, django-verdant/rca/models.py
=> Updated events for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_standard_page_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_standard_page_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_standard_page_remove_old_fields.py, django-verdant/rca/models.py
=> Update StandardPage/Index for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_rca_now_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_rca_now_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_rca_now_remove_old_fields.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/rca_now_page.html
=> Updated RCA Now pages for new taxonomy models

django-verdant/rca/migrations/0025_taxonomy_blog_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_blog_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_blog_remove_old_fields.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/rca_blog_page.html
=> Update blogs for new taxonomy models

django-verdant/taxonomy/migrations/0019_auto_20160901_1129.py, django-verdant/taxonomy/models.py
https://torchbox.codebasehq.com/projects/rca-django-cms-project/tickets/809#update-36134200
=> [809] No longer show school in programme label

django-verdant/rca/migrations/0025_remove_school_programme_from_projects.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/innovation_rca_project.html, django-verdant/rca/templates/rca/reach_out_rca_project.html
=> Removed school/programme fields from InnovationRCAProject and ReachOutRCAProject

django-verdant/rca/migrations/0025_taxonomy_sustainrca_project_add_new_fields.py, django-verdant/rca/migrations/0026_taxonomy_sustainrca_project_migrate_data.py, django-verdant/rca/migrations/0027_taxonomy_sustainrca_project_remove_old_fields.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/sustain_rca_project.html
=> Update SustainRCAProject for new taxonomy models

django-verdant/rca/api/endpoints.py, django-verdant/rca/api/serializers.py, django-verdant/rca/models.py, django-verdant/rcasite/urls.py
Configured api fields for standard pages, news, events, blogs, staff and students
=> Added WagtailAPI

django-verdant/rca/templates/rca/includes/modules/news-meta-data.html, django-verdant/rca/templates/rca/rca_blog_page.html, django-verdant/rca/templates/rca/rca_now_page.html, django-verdant/rca/templates/rca/sustain_rca_project.html, django-verdant/taxonomy/templatetags/taxonomy_tags.py
Part of taxonomy migration: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/809
=> Use historical school/programme name in a few more places

django-verdant/rca/api/serializers.py
This is required to make the intranet synchronisation work on staging
=> Get image base URL from site record

django-verdant/rca/static/rca/css/enquiry-form.less, django-verdant/rca/templates/rca/enquiry_form_page.html, django-verdant/rca/templates/rca/enquiry_form_page_ajax.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/824#update-37353988
=> Enquiry form privacy message

django-verdant/rca/static/rca/css/contact.less, django-verdant/rca/static/rca/css/desktop-large.less, django-verdant/rca/static/rca/js/site.js, django-verdant/rca/templates/rca/contact_us_page.html
=> Display contact details on page instead of modal window on small screens

django-verdant/rca/context_processors.py, django-verdant/rca/templates/rca/base.html, django-verdant/rcasite/settings/base.py, django-verdant/rcasite/settings/production.py
[Codebase ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/843)
=> [843] Add silverpop code

django-verdant/rca_show/static/rca_show/css/core.less, django-verdant/rca_show/static/rca_show/css/modules.less, django-verdant/rca_show/static/rca_show/css/variables.less
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/842
=> [842] comment out NewRail font

django-verdant/rca/app_urls.py, django-verdant/rcasite/settings/production.py, django-verdant/rcasite/urls.py, django-verdant/student_profiles/now_urls.py, django-verdant/student_profiles/urls.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/828
=> [828] Set default cache-control of whole site to 30 minutes

django-verdant/rca/templates/rca/base.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/846#update-38950471
=> [846] Insert adroll code into base template

django-verdant/rca_show/static/rca_show/css/themes.less
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/821
=> [821] Tweak width of site-name for show banner at smaller screen size so the text doesn't overlap.

django-verdant/rca/templates/rca/includes/modules/news-meta-data.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/855#update-39757609
=> Small change in header

django-verdant/rca_show/models.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/895#update-43514683
=> Use FieldPanel for show index page's "programme" field

django-verdant/rca/templatetags/rca_tags.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/864
=> [864] Do not use push state for lightbox

django-verdant/rca/templates/rca/base.html, django-verdant/requirements.txt
=> 906 favicon

django-verdant/rca/models.py
=> Allow only one date format in enquiry form page

django-verdant/rca_ldap/settings.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/909
=> Change LDAP groups "Media Relations & Marketing" -> "Communications & Marketing"

django-verdant/rca/static/rca/css/desktop-small.less, django-verdant/rca/static/rca/css/streamfield-blocks/showcase.less, django-verdant/rca/templates/rca/blocks/showcase_block.html, django-verdant/rca/templates/rca/home_page_2018.html
- large central image and associated repositioning of other slides
- mobile styling
- text spacing and positioning
=> Showcase styling

django-verdant/rca/static/rca/css/components/hero-search.less, django-verdant/rca/static/rca/css/components/hero.less, django-verdant/rca/static/rca/css/components/homepage-heading.less, django-verdant/rca/static/rca/css/core.less, django-verdant/rca/static/rca/css/streamfield-blocks/video-block.less, django-verdant/rca/static/rca/css/variables.less, django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/blocks/video_block.html, django-verdant/rca/templates/rca/home_page_2018.html
I added a components folder, I just couldn't bring myself to add more to the individual modules files. My argument to myself was also that if more work needs to be done on this codebase in future it might be useful to have this new stuff kept separate from the legacy code to make it easier to keep. It feels neater to me to do it this way, but if you'd rather I split this out into the modules files @helenb I will do.
I haven't done a huge amount on mobile as the design we have is so different from the desktop version that it seemed more sensible to wait for a proper design.
I also need to speak to @richbrennan to figure out how to get the images into the programme finder search results, so this is a little bit of WIP
=> hero frontend

django-verdant/rca/static/rca/css/components/homepage-heading.less, django-verdant/rca/static/rca/css/core.less, django-verdant/rca/static/rca/css/streamfield-blocks/events.less, django-verdant/rca/static/rca/css/streamfield-blocks/showcase.less, django-verdant/rca/static/rca/js/events-block.js, django-verdant/rca/static/rca/js/programme-finder.js, django-verdant/rca/static/rca/js/showcase-block.js, django-verdant/rca/templates/rca/blocks/events_block.html, django-verdant/rca/templates/rca/blocks/news_block.html, django-verdant/rca/templates/rca/home_page_2018.html
Events styling, and I have also moved the js from the template into separate js files. Note that I have recreated styles for now even where they are similar - we may be able to refactor if time later.
=> 962 events

django-verdant/rca/static/rca/css/streamfield-blocks/news.less
Changes to news for Ben's new mobile design.
=> 961 news mobile changes

django-verdant/rca/static/rca/css/components/homepage-block.less, django-verdant/rca/static/rca/css/components/slider.less, django-verdant/rca/static/rca/css/streamfield-blocks/events.less, django-verdant/rca/static/rca/css/streamfield-blocks/news.less, django-verdant/rca/static/rca/css/streamfield-blocks/showcase.less, django-verdant/rca/static/rca/css/streamfield-blocks/testimonial.less, django-verdant/rca/static/rca/css/streamfield-blocks/two-column-block.less, django-verdant/rca/static/rca/js/events-block.js, django-verdant/rca/static/rca/js/showcase-block.js, django-verdant/rca/templates/rca/blocks/events_block.html, django-verdant/rca/templates/rca/blocks/showcase_block.html, django-verdant/rca/templates/rca/blocks/testimonials_block.html, django-verdant/rca/templates/rca/blocks/two_column_block.html
this will likely impact most if not all the blocks / overall page layout. Would probably be good to merge before starting to look at the new tickets
=> 980 spacing

README.md
Beth please could you read through for sense and let me know if I've missed anything out.
=> Add some documentation on front-end in the build

django-verdant/rca/views.py
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1003
=> [1003] Increase search dropdown rendition size to 400x400

django-verdant/rca_show/management/commands/students_report_2019.py
Adapted students_report_2018.py for this year's spreadsheet
=> Adapted students_report_2018.py for 2019

django-verdant/rca/templates/rca/enquiry_form_page.html, django-verdant/requirements.txt
Also added recaptcha requirement to fix the build locally
=> Adding new site js to enquiry_form_page

django-verdant/rca_ee/templates/rca_ee/booking_form_page.html, django-verdant/rca_ee/templates/rca_ee/form_page.html
[ticket link](https://projects.torchbox.com/projects/rca-website-rebuild/tickets/187)
=> Missing js include which is breaking the nav

Vagrantfile, django-verdant/rca_show/static/rca_show/css/themes.less
Fix for issue mentioned in slack, testing on staging
=> Removing hover/active link colour from theme-show2015

django-verdant/rca/context_processors.py, django-verdant/rca/templates/rca/includes/login_disabled_message.html, django-verdant/rcasite/admin_views.py, django-verdant/rcasite/settings/base.py, django-verdant/rcasite/urls.py, django-verdant/student_profiles/auth.py, django-verdant/wagtailadmin_overridden_templates/templates/wagtailadmin/login.html
=> Disable login to Wagtail admin

django-verdant/rcasite/settings/base.py, django-verdant/rcasite/urls.py
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/133
=> Add wagtail sitemap

.circleci/config.yml
Sets auth method to allow for new default after postgres image upgrade.
=> Set postgres auth method to trust

django-verdant/rcasite/urls.py
Security advisory: https://github.com/wagtail/wagtail/security/advisories/GHSA-v2wc-pfq2-5cm6
=> Migitate CVE-2020-11001 by disabling revision comparison feature

django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/includes/modules/navigation/primarynav.html, django-verdant/rca/templates/rca/includes/modules/outdated-banner.html
Accessibility changes - see https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1066
=> 1066 accessibility audit changes

django-verdant/rca/static/rca/css/components/sitewide-alert.less, django-verdant/rca/static/rca/css/core.less, django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/includes/modules/sitewide-alert.html
[Codebase ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1069#update-63532855)
I haven't been able to test this locally as it relies upon JS from the live site, however it uses the same styles as the component created for the RCA rebuild site, so in theory should be the same.
It may need revisiting once the BE is in place here too.
=> [1069] Site-wide overlay alert message (FE)

django-verdant/rca/static/rca/js/populate-primary-nav.js, django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/includes/modules/navigation/primarynav.html
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/508
=> [508] Accessibility updates

django-verdant/rca/static/rca/css/components/search.less, django-verdant/rca/templates/rca/includes/modules/navigation/primarynav.html, django-verdant/rca/templates/rca/includes/modules/navigation/standoutnav.html
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/501
=> [501] Update quicklinks and fix search icon

django-verdant/rca/templates/rca/new_student_page.html, django-verdant/rca/templates/rca/tags/staff_related.html, django-verdant/rca/templates/rca/tags/students_related.html, django-verdant/rca/templates/rca/tags/students_related_work.html, django-verdant/rca_show/templates/rca_show/student.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1076#update-64121365
=> [1076] MA and related student images

django-verdant/rca/api/filters.py
For [ticket 1072](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1072)
=> News & events API feed on new pages > update to events

django-verdant/rca/templates/rca/includes/footer.html
For [ticket 1102](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1102)
=> Remove trademark notice from site footer

django-verdant/rca/templates/404.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1120
This is a compromise prior to FE involvement, staged, not too pretty but has the links they want.
=> 1120 - Hardcode basic content into verdant 404 page

django-verdant/rca/templates/rca/stream_page.html
Implements: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1224
Adds the new streaming code from: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1224#update-67498511
=> [1224] update stream page for 2021 player code

django-verdant/archiveit/urls.py, django-verdant/archiveit/views.py, django-verdant/rca/models.py, django-verdant/rca/templates/rca/archive_it.html, django-verdant/rcasite/settings/base.py, django-verdant/rcasite/urls.py
WORK IN PROGRESS
Implements: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1199
- Adds page of links to student pages fro archive-it crawler
=> [1199] Show list of urls for archive-it crawler

django-verdant/requirements.txt, django-verdant/student_profiles/forms.py
This branch was started by Tom. He added the python-image lib to avoid using Pillow for student areas.
I tested it but it needed a couple of changes to check the file type with the different image library.
=> Wip 1107 image CVE

django-verdant/rca/static/rca/css/streamfield-blocks/callout.less, django-verdant/rca/static/rca/css/variables.less, django-verdant/rca_show/static/rca_show/css/variables.less
Lots of changes due to linting, only change was #0096ff to #077aca for contrast reasons
=> changing inaccessible blue to 077aca

django-verdant/rca/templates/rca/includes/header.html, django-verdant/rca/templates/rca/new_student_page.html
Removes 'stuff' from the verdant site that we don't want the archive to pick up
=> Tweaks for archive
