torchbox/verdant-rca

django-verdant/rca/templatetags/rca_tags.py
https://sentry.torchbox.com/torchbox/rca-main-site/issues/2034/
The code assumed that every single content type had manual adverts
=> [Sentry #2034] Fixed crash when looking up manual adverts for sidebar

django-verdant/rca/templatetags/rca_tags.py, django-verdant/rca_show/migrations/0008_showindexpage_hide_animation_videos.py, django-verdant/rca_show/models.py, django-verdant/rca_show/templates/rca_show/student.html, django-verdant/rca_show/templates/rca_show/student_2016.html
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/830
We need to hide animation videos in every carousel except on the private animation show pages.
We previously relied on a bit of template logic to control this, but that logic broke recently. This commit replaces this logic with a "hide_animation_videos" checkbox (default to checked) that an administrator can uncheck on pages where animation videos should be allowed.
=> [#830] Added hide_animation_videos flag to ShowIndexPage

.drone.yml
Requires Django 1.9 because ruuning the migrations on Django 1.8 maxes out Drone's memory
=> Run tests on Drone

django-verdant/rca/migrations/0040_rcaimage_collection.py, django-verdant/rca/migrations/0041_auto_20160905_1120.py, django-verdant/rca/models.py, django-verdant/requirements.txt, django-verdant/student_profiles/templates/student_profiles/admin_base.html, django-verdant/student_profiles/templates/student_profiles/login.html
The show views contain lots of untested custom logic that may be broken by a Wagtail update so this should not be merged before show 2016 is over.
TODO:
=> Update Wagtail to 1.6

django-verdant/rca/models.py
We should recognise mphil and phd students with an unknown graduation year as current students.
Refs:
* [Ticket #829](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/829)
=> Ticket #829 - Fix current phd and mphil students

django-verdant/rca/migrations/0050_cb835_migrate_renamed_programmes.py
Addresses:
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/835
RCA rename their programmes sometimes but sometimes this has been
represented as a new programme instead of renaming an existing one. The
result is we have two programme records representing the same programme.
This migration remaps any pages that use a programme with an old name to
instead use the new renamed one.
Mapping is defined in:
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/835#update-37475581
To save development time, we only do this for content types that have a lot 
of pages. Other page types will be changed manually.
List of content types defined in:
https://projects.torchbox.com/projects/rca-django-cms-project/tickets/835#update-38772748
=> [835] Added migration to reassign pages with a renamed programme

django-verdant/rca/management/commands/set_page_random_order.py, django-verdant/rcasite/wsgi.py
* We need to use `django.apps.apps.get_models()` instead of `django.db.models.get_models()`.
* We should run it hourly
=> Fix the set_page_random_order command

django-verdant/rcasite/settings/base.py, django-verdant/rcasite/utils.py
Some RCA Show templates use dynamic base template, so we need to pass it into context during offline compression.
Related #108
=> Fix offline compression

django-verdant/requirements.txt
Currently CI breaks because of that.
=> Update psycopg2 to 2.7.4 in order to fix CI

django-verdant/rca_ee/wtforms.py
Field type was only being set during save, this meant that during preview stages where no save takes place the page would error when it attempted to render the form as `field_type=''`. This change ensures that `field_type` is kept in sync with any change to `new_field_type`.
=> [884] Ensure that the field_type is always set

django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/full_width.html, django-verdant/rca/templates/rca/home_page_2018.html
- Add extra blocks to base.html to allow overrides to aside and inner div
- Create a full_width.html template which will add the full width overrides
- Make the new home page template extend full_width.html
=> Add option for full width pages with no sidebar

django-verdant/rca/templates/rca/base.html
- For now, simply remove the call to pushstate.js in base.html
- At a later date, requires a proper tidy up to remove all associated code and styling.
=> Remove push state across the site

django-verdant/rca/models.py
See ticket https://projects.torchbox.com/projects/rca-django-cms-project/tickets/1014
=> 1014 Updated homepage packery to get future events instead of past ones

django-verdant/rca/api/endpoints.py, django-verdant/rca/api/filters.py, django-verdant/rcasite/settings/dev.py
Updates the current API to allow filtering content by programme type. 
We plan to make this request in the new live site for related content areas. Also added a filter to bring back EventItems ordered by date closest to `now`
=> Update api to allow querying by programme type

django-verdant/rca/templates/rca/base.html
Removing GA as per https://projects.torchbox.com/projects/rca-website-rebuild/tickets/50. When this is deployed we need to let Chris Danks / SEO team know.
=> Removing GA code

django-verdant/rcasite/settings/base.py, django-verdant/rcasite/urls.py, django-verdant/rcasitemaps/sitemap_generator.py, django-verdant/rcasitemaps/views.py
https://projects.torchbox.com/projects/rca-website-rebuild/tickets/133
Due to the older version of wagtail the generator is from a newer version from wagtail.contrib.sitemaps, and the views are a straight copy from the newer version. This is so we can paginate the sitemap and avoid herokus 30 second threshold
=> Add wagtail sitemap

.circleci/config.yml
Copied from https://github.com/torchbox/rca-wagtail-2019/pull/396.
UPSTREAM_REPO and DEPLOYMENT_KEY are set on staging and production Heroku apps. 
DEPLOYMENT_KEY should be added as an environment variable to Circle CI.
=> Circle CI changes to the new deployment config

django-verdant/rca/api/endpoints.py
This is required to allow the new site to identify related news and events by tag
=> [456] Allow filtering of page results by tag in the API

.circleci/config.yml
So the archive url doesn't 404, E.G
```
Get:4 http://deb.debian.org/debian stretch/main amd64 rsync amd64 3.1.2-1+deb9u2 [393 kB]
Err:5 http://deb.debian.org/debian stretch/main amd64 libldap2-dev amd64 2.4.44+dfsg-5+deb9u3
404  Not Found
Fetched 923 kB in 0s (4665 kB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openldap/libldap2-dev_2.4.44+dfsg-5+deb9u3_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
=> Run apt-get update before ldap is installed in the CI

django-verdant/rca/static/rca/css/components/sitewide-alert.less, django-verdant/rca/static/rca/css/core.less, django-verdant/rca/templates/rca/base.html, django-verdant/rca/templates/rca/includes/modules/sitewide-alert.html, django-verdant/rca/templatetags/rca_tags.py
Add templatetag that gets the site-wide alert data from the API on the rebuild site.
See: https://github.com/torchbox/rca-wagtail-2019/pull/450
=> WIP: 1069 - Site-wide alert

django-verdant/rcasite/settings/production.py, django-verdant/requirements.txt
Package has been removed from PyPi.
Copied django smtp config for mailgun directly from `rca-wagtail-2019`. Have copied config from the 2019 staging env too, will test on staging.
=> Remove django-mailgun dependency

django-verdant/rca/navigation.py
Fixes the Navigation API wrapper so that cache is correctly used.
Please double check this in a local dev environment before merging as I wasn't able to get a full environment running in the time I had for this.
=> Fix cache in navigation API

django-verdant/rca/static/rca/css/modules.less
Ticket [#2445](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2445#update-69556411).
Update colours to meet contrast requirements.
The `.meta-data` class is used on various other templates and therefore they will be overridden too, but my assumption is we'll want this change to be global anyway.
=> [2445] Improve contrast to meet accessibility requirements

django-verdant/rca/static/rca/css/components/app.less
Ticket [#2447](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2447).
In order to prevent the main navigation from being tab focused, apply the same method as used on the new site.
I've not been able to test this properly locally as I couldn't easily figure out how to add navigation items to the header.
=> [2447] Prevent main navigation from being focused when it’s closed

django-verdant/rca/static/rca/css/core.less, django-verdant/rca/static/rca/css/desktop-small.less, django-verdant/rca/static/rca/css/modules.less, django-verdant/rca/static/rca/css/variables.less
Ticket [#2446](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2446).
Update link colour to meet contrast requirements.
I've reinstated the cookie notice colour, as the new blue fails contrast against the dark grey background.
=> [2446] Add new colour to improve link contrast

.circleci/config.yml, README.md, django-verdant/Dockerfile, django-verdant/dev.Dockerfile, django-verdant/requirements.txt
This PR updates a few things just to get the site running locally with docker. This codebase is very old and we hadn't planned on doing work on it when we moved it to Heroku, however, we now need to deploy some small FE changes so the site can be crawled by an archive tool.
Whilst doing this, I realised we will have the same issues when we try and deploy the site again so Dockerfile and dev.Dockerfile have been updated.
Staging deploys ok now https://app.circleci.com/pipelines/github/torchbox/verdant-rca/566/workflows/b19c01f3-4fdd-4bd3-a2e9-c0ed753e03c8
=> Fixups for local docker development

django-verdant/rca/static/rca/css/components/header.less, django-verdant/rca/templates/rca/includes/header.html
Part of the legacy wind down - menu/search buttons removed and new label added. I somehow managed to get the ticket ID wrong on the branch name, sorry about that.
Ticket here: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2535
https://github.com/torchbox/verdant-rca/assets/2553896/bb134976-886e-455d-9158-8dcf2f1a1a9e
=> [2535/1090] Add logo label and remove menu/search buttons
